spring:
  application:
    name: STOCK-SERVICE-CONFIG-SERVER-prod
    
eureka:
  instance:
    #hostname: localhost
    prefer-ip-address: true
  client:
    enabled: true
    service-url:
      #default-zone: http://localhost:8761/eureka
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
